image: node:20

stages:
  - install
  - lint
  - format
  - test

variables:
  NODE_ENV: 'test'

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g pnpm

install:
  stage: install
  script:
    - pnpm install

lint:
  stage: lint
  script:
    - pnpm run lint

format:
  stage: format
  script:
    - pnpm run check-format

test:
  stage: test
  script:
    - pnpm install
    - pnpm run test -- --coverage
  artifacts:
    paths:
      - coverage/
